"""Add Favorite Color column to Users table.

Revision ID: ba55c8b9e07c
Revises: b1080816160d
Create Date: 2019-03-10 20:37:58.521880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba55c8b9e07c'
down_revision = 'b1080816160d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_favorite_color'), 'users', ['favorite_color'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_favorite_color'), table_name='users')
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
